---
Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Warning

ReverseProxy:
  Clusters:
    kc:
      Destinations:
        kc:
          Address: http://kc.localhost:8080

  Routes:
    gitlab_auth:
      Transforms:
        - RequestHeadersCopy: 'true'
        - PathSet: "/realms/master/protocol/openid-connect/auth"
        - DisableSecureCookies: 'true'
    gitlab_token:
      Transforms:
        - RequestHeadersCopy: 'true'
        - PathSet: "/realms/master/protocol/openid-connect/token"
        - DisableSecureCookies: 'true'
    gitlab_rest:
      Transforms:
        - RequestHeadersCopy: 'true'
        - DisableSecureCookies: 'true'
AppConfig:
  KeyCloak:
    Url: "http://kc.localhost:8080"
    AppId: "e1bd1f68329950a67a9a7a2b11d5f8fd8799ec3ea2f314d7b4aa90961d61b04a"
    AppSecret: "gloas-1c8b6d60a86e8c7b054a0d443bc8520821f8a88d0ac3579e020f7bfa6a84b279"
  GitLab:
    Url: "http://gitlab.localhost"
    PAT: "glpat-tcHWEY7BL3NrMR5yZp9S"
