
name: CI - On Master Branch Tag
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["CI - On Master Branch Push"]
    types:
      - completed
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build-push:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: red55/mm-openid-proxy
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Dump meta
        run: |
          echo "Meta-tags: ${{ steps.meta.outputs.tags }}"
          echo "Meta-labels: ${{ steps.meta.outputs.labels }}"
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Red55.Mattermost.OpenId.Proxy/Dockerfile
          push: true
          tags: "${{ env.DOCKER_METADATA_OUTPUT_TAGS }}"
          labels: "${{ env.DOCKER_METADATA_OUTPUT_LABELS }}"

#        run: |
#          docker buildx build --tag red55/mm-openid-proxy:latest -f Red55.Mattermost.OpenId.Proxy/Dockerfile .
#          docker push red55/mm-openid-proxy:latest
